
FROM python:3-slim

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

RUN pip3 install python-telegram-bot>=12.0.0

RUN mkdir -p /usr/app/
WORKDIR /usr/app
COPY --chmod=744 ./telebot.py .
CMD python3 /usr/app/telebot.py